using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using System.Windows.Forms;
using OfficeOpenXml;
using InsurancePayrollValidator;
class Regression {
 static string dir; static int count; static List<string> log=new List<string>();
 static object Call(Type t,string name,object target,params object[] args){try{return t.GetMethod(name,BindingFlags.NonPublic|BindingFlags.Public|BindingFlags.Static|BindingFlags.Instance).Invoke(target,args);}catch(TargetInvocationException e){throw e.InnerException;}}
 static void Eq(decimal got,decimal want,string why){if(got!=want)throw new Exception(why+": expected "+want+", got "+got);count++;}
 static decimal N(ExcelWorksheet w,int r,int c){return Convert.ToDecimal(w.Cells[r,c].Value??0);}
 static string Make(string name,string[] headers,params object[][] rows){string path=Path.Combine(dir,name+".xlsx");using(var p=new ExcelPackage()){var w=p.Workbook.Worksheets.Add("자료");for(int c=0;c<headers.Length;c++)w.Cells[1,c+1].Value=headers[c];for(int r=0;r<rows.Length;r++)for(int c=0;c<rows[r].Length;c++)w.Cells[r+2,c+1].Value=rows[r][c];p.SaveAs(new FileInfo(path));}return path;}
 static Dictionary<string,Charge> Parse(string path,string ins){var d=new Dictionary<string,Charge>();var logs=new List<Recognition>();Call(typeof(Processor),"ReadCharges",null,path,ins,ins,d,logs);if(d.Count==0)throw new Exception("parse failed "+String.Join(";",logs.Select(x=>x.Detail)));return d;}
 static List<ResultRow> Compare(Dictionary<string,Charge> c,Dictionary<string,Person> p=null){return (List<ResultRow>)Call(typeof(Processor),"Compare",null,p??new Dictionary<string,Person>(),c);}
 static ExcelPackage Ui(List<ResultRow> rows){var p=new ExcelPackage();Call(typeof(Processor),"WriteUiIndividualSheet",null,p.Workbook.Worksheets.Add("UI個人"),rows,new BillingPeriod{Year=2026,Month=9});Call(typeof(Processor),"WriteUiSummarySheet",null,p.Workbook.Worksheets.Add("UI集計"),rows,new BillingPeriod{Year=2026,Month=9});return p;}
 static string[] hh={"성명","주민등록번호","사업장관리번호","회계","산출보험료","요양산출보험료","정산금액","요양정산보험료","고지금액","요양고지보험료","가입자총납부할보험료"};
 static string[] ph={"성명","주민등록번호","사업장관리번호","총부담금계본인기여금원","총부담금계사용자부담금원","정산보험료본인기여금원","정산보험료사용자부담금원"};
 static string Health(string name,decimal hc,decimal lc,decimal hs,decimal ls,string account="00"){return Make(name,hh,new object[]{"가상정산","900101","11111111111",account,hc,lc,hs,ls,hc+hs,lc+ls,hc+lc+hs+ls});}
 static string Result(string name,InputSet input){string path=Path.Combine(dir,name+".xlsm");Processor.Run(input,path);return path;}
 static void Assign(string result,string fund){using(var f=new MainForm()){Call(typeof(MainForm),"LoadResultIntoUi",f,result);var model=(IndividualDashboardModel)typeof(MainForm).GetField("individualDashboard",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(f);var drafts=(Dictionary<string,string>)typeof(MainForm).GetField("reviewFundDrafts",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(f);foreach(var x in model.Rows)drafts[(string)Call(typeof(MainForm),"ReviewKey",f,x)]=fund;Eq(Convert.ToDecimal(Call(typeof(MainForm),"PersistReviewChangesCore",f,result)),model.Rows.Count,"manual assignment count");}using(var p=new ExcelPackage(new FileInfo(result))){var w=p.Workbook.Worksheets["UI개인별데이터"];for(int r=2;r<=w.Dimension.End.Row;r++)if(w.Cells[r,2].Text!=fund)throw new Exception("fund reload");}}
 static void WorkerCheck(string path,decimal[] expected,decimal[] settlements){string output=SubmissionGenerator.Create(path,dir,false,new SubmissionInfo{InstitutionName="가상검증",RecipientCode="TEST"});using(var p=new ExcelPackage(new FileInfo(output))){var w=p.Workbook.Worksheets[1];int[] cols={16,20,24,28,32},settle={15,19,23,27,31};foreach(int c in new[]{14,18,22,26,30}){if(String.IsNullOrWhiteSpace(w.Cells[7,c].Formula))throw new Exception("worker current formula overwritten "+c);count++;}for(int i=0;i<5;i++){Eq(N(w,7,cols[i]),expected[i],"worker output total "+i);if(settlements!=null)Eq(N(w,7,settle[i]),settlements[i],"worker settlement "+i);}}}
 [STAThread] static int Main(string[] args){dir=Path.GetFullPath(args[0]);Directory.CreateDirectory(dir);Environment.SetEnvironmentVariable("SOCIAL_INSURANCE_TEST_HOME",Path.Combine(dir,"settings"));Application.EnableVisualStyles();try{
  if(args.Contains("--baseline")){
   using(var p=Ui(Compare(Parse(Health("baseline-health",0,0,-45540,-5940),"건강보험"))))log.Add("BASELINE health UI employer: "+(N(p.Workbook.Worksheets[1],2,23)+N(p.Workbook.Worksheets[1],2,25))+"; correct=-51480");
   string pp=Make("baseline-pension",ph,new object[]{"가상정산","900101","11111111111",80000,81000,-20000,-19000});using(var p=Ui(Compare(Parse(pp,"국민연금"))))log.Add("BASELINE pension UI employer: "+N(p.Workbook.Worksheets[1],2,27)+"; correct=81000");
   string rr=Result("baseline-worker",new InputSet{HealthOther=Health("baseline-health2",0,0,-45540,-5940),Pension=pp});Assign(rr,"교특회계");string oo=SubmissionGenerator.Create(rr,dir,false,new SubmissionInfo{InstitutionName="가상검증"});using(var p=new ExcelPackage(new FileInfo(oo))){var w=p.Workbook.Worksheets[1];log.Add("BASELINE worker name present="+(!String.IsNullOrWhiteSpace(w.Cells[7,6].Text))+", settlement health="+N(w,7,15)+", care="+N(w,7,19)+", pension="+N(w,7,23)+"; correct=-45540,-5940,-19000");}File.WriteAllLines(Path.Combine(dir,"baseline-reproduction.txt"),log);Console.WriteLine(String.Join(Environment.NewLine,log));return 0;
  }
  PayrollSettlements();
  var real=Parse(args.Length>1?args[1]:Health("attachment-shape",0,0,-45540,-5940),"건강보험");var c=real.Values.Single();Eq(c.CompareAmount,-51480,"actual subscriber total");Eq(c.HealthCurrent+c.LongTermCurrent,0,"actual current excludes refund");Eq(c.EmployerAmount,-51480,"actual employer derived separately");
  var cp=new Person{Key=c.Key,Name=c.Name,Birth=c.Birth,Source="공무원",Fund="계약제교원",Pension=1};var people=new Dictionary<string,Person>{{c.Key,cp}};var matched=Compare(real,people).First(x=>x.Insurance=="건강보험");Eq(matched.Charge,-51480,"actual matched charge");Eq(matched.Employer,-51480,"actual matched employer");
  using(var p=Ui(Compare(real))){Eq(N(p.Workbook.Worksheets[1],2,23)+N(p.Workbook.Worksheets[1],2,25),-51480,"actual UI employer");}log.Add("PASS actual attachment parser, matched and insurance-only health totals");
  foreach(var a in new[]{new decimal[]{100000,13000,-20000,-2600},new decimal[]{100000,13000,20000,2600},new decimal[]{100000,13000,-100000,-13000},new decimal[]{100000,13000,0,0}}){var d=Parse(Health("health"+count,a[0],a[1],a[2],a[3]),"건강보험");using(var p=Ui(Compare(d))){Eq(N(p.Workbook.Worksheets[1],2,7),a.Sum(),"health current plus settlement once");Eq(N(p.Workbook.Worksheets[1],2,23)+N(p.Workbook.Worksheets[1],2,25),a.Sum(),"health employer");}}
  var gov=Parse(Health("gov",100000,13000,-20000,-2600,"95"),"건강보험");Eq(gov.Values.Single().EmployerAmount,0,"public employer excluded");
  var explicitH=Make("explicit",hh.Concat(new[]{"기관부담금","기관정산보험료계"}).ToArray(),new object[]{"가상정산","900101","11111111111","00",100000,13000,-20000,-2600,80000,10400,90400,70000,-10000});var explicitC=Parse(explicitH,"건강보험");Eq(explicitC.Values.Single().EmployerAmount,70000,"explicit employer respected");using(var p=Ui(Compare(explicitC))){Eq(N(p.Workbook.Worksheets[1],2,23)+N(p.Workbook.Worksheets[1],2,25),70000,"asymmetric UI employer");}log.Add("PASS health positive/negative/zero/net-zero/public/explicit asymmetric employer");
  foreach(decimal settle in new[]{20000m,-20000m,-100000m,0m}){decimal total=100000+settle;var path=Make("pension"+count,ph,new object[]{"가상정산","900101","11111111111",total,total+1000,settle,settle});var d=Parse(path,"국민연금");using(var p=Ui(Compare(d))){Eq(N(p.Workbook.Worksheets[1],2,10),total,"pension personal total");Eq(N(p.Workbook.Worksheets[1],2,27),total+1000,"pension employer total");}var pc=d.Values.Single();var pay=new Person{Key=pc.Key,Name=pc.Name,Birth=pc.Birth,Source="교육공무직",Fund="교특",Pension=total,PensionSettlement=settle};using(var p=Ui(Compare(d,new Dictionary<string,Person>{{pc.Key,pay}}))){Eq(N(p.Workbook.Worksheets[1],2,12),0,"payroll settlement included once");}}
  var current=Make("current",new[]{"성명","주민등록번호","사업장관리번호","당월분본인기여금","당월분사용자부담금","정산본인기여금원","정산사용자부담금원"},new object[]{"가상정산","900101","11111111111",100000,100000,-20000,-20000});Eq(Parse(current,"국민연금").Values.Single().CompareAmount,80000,"current-only pension normalized");log.Add("PASS pension total/current headers, positive/refund/net-zero, payroll settlement");
  var health=Health("integration-health",0,0,-45540,-5940);var pension=Make("integration-pension",ph,new object[]{"가상정산","900101","11111111111",80000,81000,-20000,-19000});
  var employment=Make("employment",new[]{"성명","주민등록번호","사업장관리번호","보험료합계①②③근로자실업급여보험료","보험료합계①②③사업주실업급여보험료","보험료합계①②③사업주고안직능보험료","정산보험료③근로자실업급여보험료","정산보험료③사업주실업급여보험료","정산보험료③사업주고안직능보험료"},new object[]{"가상정산","900101","11111111111",8000,8000,7000,-2000,-2000,-1000});
  var industrial=Make("industrial",new[]{"성명","주민등록번호","사업장관리번호","보험료합계","정산보험료"},new object[]{"가상정산","900101","11111111111",5000,-1000});
  var result=Result("worker",new InputSet{HealthOther=health,Pension=pension,Employment=employment,Industrial=industrial});Assign(result,"교특회계");WorkerCheck(result,new decimal[]{-45540,-5940,-19000,-3000,-1000},new decimal[]{-45540,-5940,-19000,-3000,-1000});log.Add("PASS parser -> model -> UI manual fund save/reload -> actual Excel worker output all four insurances");
  var teacher=Result("teacher",new InputSet{HealthOther=health,Pension=pension});Assign(teacher,"계약제교원");string tx=SubmissionGenerator.Create(teacher,dir,true,new SubmissionInfo{InstitutionName="가상검증",RecipientCode="TEST"});using(var p=new ExcelPackage(new FileInfo(tx))){var w=p.Workbook.Worksheets[1];Eq(N(w,5,7),81000,"teacher pension");Eq(N(w,5,8),-45540,"teacher health");Eq(N(w,5,9),-5940,"teacher long-term");}log.Add("PASS actual teacher output health -51480 (not -102960), pension 81000");
  var wageHealth=Make("base-health",hh.Concat(new[]{"보수월액"}).ToArray(),new object[]{"가상정산","900101","11111111111","00",71900,9440,-1000,-100,70900,9340,80240,2000000});
  var wagePension=Make("base-pension",ph.Concat(new[]{"기준소득월액"}).ToArray(),new object[]{"가상정산","900101","11111111111",81000,81000,-19000,-19000,2000000});
  string wr=Result("base-worker",new InputSet{HealthOther=wageHealth,Pension=wagePension});Assign(wr,"교특회계");WorkerCheck(wr,new decimal[]{70900,9340,76000,0,0},new decimal[]{-1000,-100,-19000,0,0});log.Add("PASS worker wage-base formulas preserved; pension 2000000 * template rate -19000 = 76000, not notice total 81000");

  // Same identity across different sites must not collapse or contaminate the selected site.
  var multi=Make("multi-pension",ph,new object[]{"가상정산","900101","11111111111",100,110,20,20},new object[]{"가상정산","900101","22222222222",200,220,30,30});string mr=Result("multi",new InputSet{Pension=multi});Assign(mr,"계약제교원");foreach(var site in new[]{"11111111111","22222222222"}){string file=SubmissionGenerator.Create(mr,dir,true,new SubmissionInfo{Site=site,InstitutionName=site});using(var p=new ExcelPackage(new FileInfo(file)))Eq(N(p.Workbook.Worksheets[1],5,7),site[0]=='1'?110:220,"site-filtered teacher amount");}log.Add("PASS same name/birth across sites preserves separate employer totals");
  string reordered=Make("reordered",new[]{"성명","주민등록번호","사업장관리번호","정산보험료본인기여금원","정산보험료사용자부담금원","총부담금계본인기여금원","총부담금계사용자부담금원"},new object[]{"가상정산","900101","11111111111",-20000,-19000,80000,81000});var rc=Parse(reordered,"국민연금").Values.Single();Eq(rc.CompareAmount,80000,"settlement column preceding total personal");Eq(rc.EmployerAmount,81000,"settlement column preceding total employer");
  string sr=Path.Combine(dir,"shortterm.xlsm");File.Copy(wr,sr,true);using(var p=new ExcelPackage(new FileInfo(sr))){p.Workbook.Worksheets["UI개인별데이터"].Cells[2,34].Value=1;p.Save();}WorkerCheck(sr,new decimal[]{70900,9340,76000,0,0},new decimal[]{-1000,-100,-19000,0,0});log.Add("PASS short-term worker also preserves wage-base formulas and settlement-only inputs");
  using(var f=new MainForm())f.ManualTest202(wr,Path.Combine(dir,"manual-regression.txt"));log.Add("PASS existing manual correction/save/reload/history and original-sheet preservation regression");
  string legacy=Path.Combine(dir,"legacy.xlsm");File.Copy(wr,legacy,true);using(var p=new ExcelPackage(new FileInfo(legacy))){p.Workbook.Worksheets["UI개인별데이터"].Cells[1,40].Value=null;p.Save();}bool rejected=false;try{SubmissionGenerator.Create(legacy,dir,false);}catch(InvalidOperationException ex){rejected=ex.Message.Contains("새로 대사");}if(!rejected)throw new Exception("legacy results must request fresh reconciliation");count++;log.Add("PASS old saved result cannot silently reuse doubled/missing settlement totals");
  JobEdit(wr);
  if(args.Length>2)PensionFormat(args[2]);
  log.Add("PASS assertions="+count);File.WriteAllLines(Path.Combine(dir,"results.txt"),log);Console.WriteLine(String.Join(Environment.NewLine,log));return 0;
 }catch(Exception e){log.Add("FAIL after "+count+" assertions: "+e);File.WriteAllLines(Path.Combine(dir,"results.txt"),log);Console.WriteLine(log.Last());return 1;}}
 static void JobEdit(string source){
  string path=Path.Combine(dir,"job-edit.xlsm");File.Copy(source,path,true);
  using(var f=new MainForm()){
   Call(typeof(MainForm),"LoadResultIntoUi",f,path);
   Func<IndividualRowData> get=()=>((IndividualDashboardModel)typeof(MainForm).GetField("individualDashboard",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(f)).Rows.Single();
   var row=get();string key=(string)Call(typeof(MainForm),"StablePersonKey",null,row),fund=row.Fund;
   var checkedKeys=(HashSet<string>)typeof(MainForm).GetField("reviewCheckedKeys",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(f);checkedKeys.Add(key);Call(typeof(MainForm),"PersistReviewChangesCore",f,path);Call(typeof(MainForm),"LoadResultIntoUi",f,path);row=get();
   var before=(decimal[])Call(typeof(MainForm),"ManualValues202",null,row);
   foreach(string job in new[]{"조리실무사","교육실무사","","  교육실무사  "}){
    row=get();using(var bubble=new ReviewEditBubble202(row,"직종명 수정 검증",true,null,(values,newJob)=>Call(typeof(MainForm),"SaveManual202",f,path,key,values,newJob))){bubble.Show();Application.DoEvents();((TextBox)bubble.Controls.Find("JobNameInput",true).Single()).Text=job;
     if(job=="조리실무사")using(var bmp=new System.Drawing.Bitmap(bubble.Width,bubble.Height)){bubble.DrawToBitmap(bmp,new System.Drawing.Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save(Path.Combine(dir,"job-editor.png"));}
     ((Button)bubble.Controls.Find("SaveCorrection",true).Single()).PerformClick();if(!bubble.IsDisposed)throw new Exception("job save did not close popup");
    }
    row=get();if(row.Job!=job.Trim())throw new Exception("job save/reload failed");count++;
    if(row.Fund!=fund||!(bool)Call(typeof(MainForm),"IsReviewCompleted",f,row))throw new Exception("job-only changed fund or completed state");count++;
    if(!before.SequenceEqual((decimal[])Call(typeof(MainForm),"ManualValues202",null,row)))throw new Exception("job-only changed amounts");count++;
   }
   byte[] saved=File.ReadAllBytes(path);using(var bubble=new ReviewEditBubble202(get(),"취소 검증",true,null,(v,j)=>Call(typeof(MainForm),"SaveManual202",f,path,key,v,j))){bubble.Show();Application.DoEvents();((TextBox)bubble.Controls.Find("JobNameInput",true).Single()).Text="저장하지않음";bubble.Close();}if(!saved.SequenceEqual(File.ReadAllBytes(path)))throw new Exception("cancel changed file");count++;
   Call(typeof(MainForm),"PersistReviewChangesCore",f,path);Call(typeof(MainForm),"LoadResultIntoUi",f,path);if(get().Job!="교육실무사")throw new Exception("general save lost job");count++;
  }
  using(var p=new ExcelPackage(new FileInfo(path)))using(var original=new ExcelPackage(new FileInfo(source))){if(!p.Workbook.Worksheets["수기보정이력"].Cells.Any(c=>c.Text=="직종명"))throw new Exception("job audit missing");count++;foreach(var w in original.Workbook.Worksheets.Where(w=>w.Name.StartsWith("원본")))if(w.WorksheetXml.OuterXml!=p.Workbook.Worksheets[w.Name].WorksheetXml.OuterXml)throw new Exception("job save changed original");}
  string output=SubmissionGenerator.Create(path,dir,false,new SubmissionInfo{InstitutionName="직종반영검증"});using(var p=new ExcelPackage(new FileInfo(output))){if(p.Workbook.Worksheets[1].Cells[7,5].Text!="교육실무사")throw new Exception("submission job missing");count++;}
  log.Add("PASS job editor: blank/replacement/clear/trim, save/reopen/general save, cancel, amounts/fund/completed-state preservation, audit, originals, actual submission E7");
 }
 static Person Payroll(string path){var people=new Dictionary<string,Person>();var logs=new List<Recognition>();Call(typeof(Processor),"ReadPayroll",null,path,"교육공무직","교특",people,logs);if(people.Count!=1)throw new Exception("payroll parse count");return people.Values.Single();}
 static void PayrollSettlements(){
  string[] headers={"성명","주민등록번호","건강보험 복직정산","건강보험","건강보험 휴직정산","건강보험 연말정산","건강보험 퇴직정산","건강보험 기타정산","노인장기요양보험","장기요양 복직정산","장기요양 휴직정산","장기요양 연말정산","국민연금","국민연금 복직정산","국민연금 소급","고용보험","고용보험 퇴직정산","고용보험 연말정산","고용보험 복직정산","산재보험","산재보험 퇴직정산","산재보험 연말정산","산재보험 휴직정산","건강보험 기관부담 정산","건강보험 정산사유","건강보험 정산기간"};
  var row=new object[]{"가상정산","900101",-2000,100000,-1000,500,300,200,13000,-260,-130,65,95000,-3000,1000,10000,-100,200,-300,5000,-50,100,-150,999999,"휴직",202609};
  var x=Payroll(Make("payroll-all",headers,row));Eq(x.HealthCurrent,100000,"current excludes earlier settlement column");Eq(x.HealthSettlementHealth,-2000,"all health settlement types");Eq(x.LongTermSettlement,-325,"all long-term types");Eq(x.Health,110675,"health total settlement once");Eq(x.PensionSettlement,-2000,"pension settlement and retro");Eq(x.Pension,93000,"pension payroll total");Eq(x.EmploymentSettlement,-200,"employment all three settlements once");Eq(x.IndustrialSettlement,-100,"industrial all three settlements once");
  var h=Parse(Health("payroll-match-health",100000,13000,-2000,-325),"건강보험");var matched=Compare(h,new Dictionary<string,Person>{{x.Key,x}});Eq(matched.First(v=>v.Insurance=="건강보험").Difference,0,"parsed payroll -> comparison health");using(var p=Ui(matched))Eq(N(p.Workbook.Worksheets[1],2,9),0,"parsed payroll -> UI health difference");
  var rev=Payroll(Make("payroll-reversed",headers.Reverse().ToArray(),row.Reverse().ToArray()));Eq(rev.Health,x.Health,"column order independent");Eq(rev.Employment,x.Employment,"order independent employment");
  var total=Payroll(Make("payroll-total",headers.Concat(new[]{"건강보험 정산합계"}).ToArray(),row.Concat(new object[]{-2000}).ToArray()));Eq(total.HealthSettlementHealth,-2000,"aggregate not added to details");
  var zero=Payroll(Make("payroll-zero-total",headers.Concat(new[]{"건강보험 정산합계"}).ToArray(),row.Concat(new object[]{0}).ToArray()));Eq(zero.HealthSettlementHealth,0,"zero settlement total authoritative");
  var blank=Payroll(Make("payroll-blank-total",headers.Concat(new[]{"건강보험 정산합계"}).ToArray(),row.Concat(new object[]{null}).ToArray()));Eq(blank.HealthSettlementHealth,-2000,"blank total uses detailed settlements");
  var other=Payroll(Make("payroll-other",new[]{"성명","주민등록번호","건강보험","건강보험 기타정산합계","건강보험 기타정산1","건강보험 기타정산2","건강보험 연말정산"},new object[]{"가상급여","900101",100000,300,100,200,-50}));Eq(other.HealthSettlementHealth,250,"category subtotal excludes its details");
  var careTotal=Payroll(Make("payroll-care-total",headers.Concat(new[]{"장기요양 정산합계"}).ToArray(),row.Concat(new object[]{-325}).ToArray()));Eq(careTotal.LongTermSettlement,-325,"care aggregate without insurance suffix");
  var unknown=Payroll(Make("payroll-new-settlement",headers.Concat(new[]{"건강보험 특별정산","고용보험 복직자정산"}).ToArray(),row.Concat(new object[]{-777,88}).ToArray()));Eq(unknown.HealthSettlementHealth,-2777,"unlisted health settlement kind");Eq(unknown.EmploymentSettlement,-112,"unlisted employment settlement kind");
  log.Add("PASS payroll insurance-name matching: leave/return/year-end/termination/other, signed values, order, totals and no double counting");
 }
 static void PensionFormat(string fixture){
  var expected=new List<decimal>();string copy=Path.Combine(dir,"new-pension-format.xlsx");
  using(var p=new ExcelPackage(new FileInfo(fixture))){var w=p.Workbook.Worksheets[1];for(int r=4;r<=w.Dimension.End.Row;r++){w.Cells[r,3].Value="가상연금"+(r-3);w.Cells[r,4].Value="900101";expected.Add(N(w,r,5));}p.SaveAs(new FileInfo(copy));}
  string result=Result("new-pension-format",new InputSet{Pension=copy});Assign(result,"교특회계");
  string output=SubmissionGenerator.Create(result,dir,false,new SubmissionInfo{InstitutionName="신양식검증"});
  using(var p=new ExcelPackage(new FileInfo(output))){var w=p.Workbook.Worksheets[1];for(int r=7;r<7+expected.Count;r++){int index=Int32.Parse(w.Cells[r,6].Text.Replace("가상연금",""))-1;Eq(N(w,r,11),expected[index],"new pension current base row "+index);if(String.IsNullOrWhiteSpace(w.Cells[r,22].Formula)||String.IsNullOrWhiteSpace(w.Cells[r,24].Formula))throw new Exception("pension template formulas lost");count++;} }
  log.Add("PASS supplied pension layout "+expected.Count+" rows: E current wage -> submission K; formulas preserved");
  using(var p=new ExcelPackage(new FileInfo(copy))){var w=p.Workbook.Worksheets[1];w.Cells[4,11].Value=9999999;w.Cells[4,14].Value=-1234;w.Cells[4,15].Value=-1234;w.Cells[5,5].Value=0;w.Cells[5,11].Value=8888888;p.Save();}
  var charges=Parse(copy,"국민연금");var first=charges.Values.Single(x=>x.Name=="가상연금1");Eq(first.EmployerAmount,144586,"current-only pension total plus retro once");Eq(first.SettlementEmployer,-1234,"pension retro employer");
  result=Result("new-pension-retro",new InputSet{Pension=copy});Assign(result,"교특회계");output=SubmissionGenerator.Create(result,dir,false,new SubmissionInfo{InstitutionName="소급분검증"});
  using(var p=new ExcelPackage(new FileInfo(output))){var w=p.Workbook.Worksheets[1];for(int r=7;r<7+expected.Count;r++){if(w.Cells[r,6].Text=="가상연금1"){Eq(N(w,r,11),3070000,"prefer current over nonzero retro wage");Eq(N(w,r,23),-1234,"retro premium reaches settlement W");}if(w.Cells[r,6].Text=="가상연금2")Eq(N(w,r,11),0,"zero current must not fallback to retro wage");}}
  log.Add("PASS nonzero retro wage, zero current wage, current-only totals and separate retro settlement");
 }
}
